version: "3.8"

services:
  app:
    build: .
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: "redis://default:tT0DnQpmQKKcTTZ6@redis:6379"
      DATABASE_URL: "postgresql://postgres:d1rONeFo0KL8ZwC8@db:5432/postgres"
      RAZZLE_CLIENT_ID: "368363262826-i6ngmdb856kpnjnj3huu2bpnaoiisf3h.apps.googleusercontent.com"
      SESSION_SECRETS: "kRRrPf0PzWZpVI61 l0FjSTg65UKubndp nfgZyYkXbBAUx5zY"
    ports:
      - 8080:80

  redis:
    image: redis:6-alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: d1rONeFo0KL8ZwC8
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
